# How many distinct terms are in the sequence generated by a^b
# for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

from itertools import product


def distinct_powers_brute_short(limit=100):
    return len({a**b for a, b in product(range(2, limit+1), repeat=2)})


def distinct_powers_brute(limit=100):
    powers = []
    for a in range(2, limit+1):
        for b in range(2, limit+1):
            powers.append(a**b)
    powers = list(set(powers))
    return len(powers)


if __name__ == "__main__":
    # Note: brute force solution seems to be fast enough for the given limit
    # print(distinct_powers_brute())
    print(distinct_powers_brute_short())
